export const difficulties = [
	{ difficulty: "Any Difficulty" },
	{ difficulty: "Easy" },
	{ difficulty: "Medium" },
	{ difficulty: "Hard" },
];

export const categories = [
	{ category: "Any Category" },
	{ category: "General Knowledge" },
	{ category: "Books" },
	{ category: "Film" },
	{ category: "Music" },
	{ category: "Musicals & Theatres" },
	{ category: "Television" },
	{ category: "Video Games" },
	{ category: "Board Games" },
	{ category: "Nature" },
	{ category: "Computers" },
	{ category: "Mathematics" },
	{ category: "Mythology" },
	{ category: "Sports" },
	{ category: "Geography" },
	{ category: "History" },
	{ category: "Politics" },
	{ category: "Art" },
	{ category: "Celebrities" },
	{ category: "Animals" },
	{ category: "Vehicles" },
	{ category: "Comics" },
	{ category: "Gadgets" },
	{ category: "Anime & Manga" },
	{ category: "Cartoons & Animations" },
];
